### ISSUE TITLE
frozen_graph.pb  not working

### ISSUE THREAD

**Issue by angyee** [TannerGilbert/Tutorials#10]
hi
as per your video : https://www.youtube.com/watch?v=HjiBbChYRDw

i have created my own custom model, but after running in Jupiter notebook to show the result, then showing only images not with bounding box of labeled part , why?

i have trained model for 20000 steps and batch queue size is 50 in config file, rest is everything same . why ?

@TannerGilbert

**Comment by angyee** [comment]
> hi
> as per your video : https://www.youtube.com/watch?v=HjiBbChYRDw
> 
> i have created my own custom model, but after running in Jupiter notebook to show the result, then showing only images not with bounding box of labeled part , why?
> 
> i have trained model for 20000 steps and batch queue size is 50 in config file, rest is everything same . why ?
> 
> @TannerGilbert

working with showing results on which contains only single damage area labled in image. and multiple damage area labeled image is not showing results with bounding box , why ?

**Comment by TannerGilbert** [comment]
It's hard to say. Are you sure you followed the steps for creating your data-set correctly?
