### ISSUE TITLE
nvidia-smi not showing any running process while training the model

### ISSUE THREAD

**Issue by angyee** [TannerGilbert/Tutorials#11]
![Screenshot from 2019-08-21 16-03-29](https://user-images.githubusercontent.com/17041720/63425423-1ddbe200-c42e-11e9-94ad-f97e4dbdbf12.png)

**Comment by TannerGilbert** [comment]
When using ubuntu I also sometimes had problems with using tensorflow gpu. One thing that caused problems for me was that I had both tensorflow and tensorflow gpu installed. Make sure you only have tensorflow installed.

```
pip uninstall tensorflow
pip install tensorflow-gpu
```
