### ISSUE TITLE
Problem with Uber Ludwig

### ISSUE THREAD

**Issue by doedelsnj** [TannerGilbert/Tutorials#12]
I did everything like it was shown in the video: https://www.youtube.com/watch?v=uSOsos2eKHI. But as soon as I run the training it says AssertionError: Model definition does not define any input features. Even though i have defined the input features.

Thanks for the help.

**Comment by TannerGilbert** [comment]
Are you sure you used the code provided on my Github. https://github.com/TannerGilbert/Tutorials/tree/master/Uber%20Ludwig%20Introduction. If so can you tell me the version of Ludwig you are working with?

**Comment by doedelsnj** [comment]
Yeah I did, my version is 0.2.1. Thanks again for your help.

[Terminal Output.txt](https://github.com/TannerGilbert/Tutorials/files/3596076/Terminal.Output.txt)

**Comment by TannerGilbert** [comment]
Solved by https://github.com/uber/ludwig/issues/515
