### ISSUE TITLE
Unable to convert .pb to tflite format (Mobile support)

### ISSUE THREAD

**Issue by acarmon** [TannerGilbert/Tutorials#13]
You got an excellent "Creating your own object detector" tutorial! :-)
But when trying to build tflite file from the saved_model.pb i get an error...

I saw the following the solution on stackoverflow:
https://stackoverflow.com/questions/57927688/tensorflow-conversion-from-frozen-pb-to-tflite
But running the following command:
tflite_convert --output_file=converted_model.tflite --graph_def_file=saved_model.pb --input_arrays=input --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3  --input_shape=1,300,300,3 --allow_custom_ops

**Error:**
Traceback (most recent call last):
  File "c:\users\carmo\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\python\lite.py", line **608, in from_frozen_graph
    graph_def.ParseFromString(file_content)
google.protobuf.message.DecodeError: Error parsing message**
.
  File "c:\users\carmo\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\python\lite.py", line 615, in from_frozen_graph
    **file_content = file_content.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 3: invalid start byte**

**Comment by acarmon** [comment]
Are the output_arrays correct?

**Comment by TannerGilbert** [comment]
I recently wrote a guide on how to convert a Tensorflow object detection model to Tensorflow Lite. https://gilberttanner.com/blog/convert-your-tensorflow-object-detection-model-to-tensorflow-lite
