### ISSUE TITLE
how to get mAP and precision and recall values for tensorflow object detection API?

### ISSUE THREAD

**Issue by angyee** [TannerGilbert/Tutorials#18]
I have created a custom TensorFlow object detection api, now I want to get the
values of mAP and precision and recall? how?

using your video on youtube
https://www.youtube.com/watch?v=HjiBbChYRDw
@TannerGilbert

**Comment by TannerGilbert** [comment]
You can use the COCO detection metrics.
- https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md#coco-detection-metrics
- https://stackoverflow.com/questions/52982574/calculating-the-map-from-scores-obtained-in-tensorflow-object-detection-api
