### ISSUE TITLE
Issue with scaling 

### ISSUE THREAD

**Issue by ashkaneliasy** [TannerGilbert/Tutorials#2]
Hi, 

Thank you for this amazing tutorial and RNN code. I am using your method to predict stock prices, but unfortunately I encounter an error that seems to be coming from normalisation part, but I am unable to find the issue and need to ask for your kind help. Basically I am training network with this years stock prices, and asking it to predict the next prices. After the inverse transform function, the prices don't match with the original ones for the next year data. I made a plot, and there seem to be an offset. I cannot figure out why this is happening. 

Attached is my code. I really appreciate your time in advance, solving this minor issue would be extremely valuable to me. 
[Forecast.zip](https://github.com/TannerGilbert/Tutorials/files/2922405/Forecast.zip)

Thanks,

**Comment by TannerGilbert** [comment]
Sorry for not replying for so long. I completely forgot about this issue after I took a first look but if you are still searching for answers I think that you should just increase the model size and training epochs. Furthermore you should note that these technique isn't made for predicting long times in the future and should rather be used to predict the next few data-points.

Again I'm sorry for not answering for such a long time. Hope this still was somewhat helpful. If you have any more questions fell free to ask.
