### ISSUE TITLE
run_inference_for_single_image

### ISSUE THREAD

**Issue by yongen9696** [TannerGilbert/Tutorials#21]
please check your the function run_inference_for_single_image in object_detection_with_own_model.ipynb. some required arguments need to be passing in.

**Comment by TannerGilbert** [comment]
What do you mean with "some required arguments are passing in"?

**Comment by yongen9696** [comment]
sorry for wrong phrase was used, updated with correct sentence. in the function, i think another 2 variables need to pass in, tensor_dict and sess.

**Comment by TannerGilbert** [comment]
The tensor_dict and sess are created before calling the function and can therefore be used in it. But it's also fine if you pass them as arguments. But it's also working if you don't
