### ISSUE TITLE
Tensorflow object detection API vs Keras?

### ISSUE THREAD

**Issue by balavenkatesh3322** [TannerGilbert/Tutorials#24]
I used Tensorflow object detection API for custom object detection. I am a little confused, already we have TensorFlow object detection API then why we need to use Keras with TensorFlow for object detection. 

Please clarify my doubt with a simple example and use case.

Thanks!!

**Comment by TannerGilbert** [comment]
What do you mean by "why we need to use Keras with TensorFlow for object detection." exactly?
