### ISSUE TITLE
could you paste all code?

### ISSUE THREAD

**Issue by freshrich001** [TannerGilbert/Tutorials#26]
I want to have a try.But i found that this code could not run correct.Is there any code have gone?Thanks.

**Comment by freshrich001** [comment]
I have run the "Recommendation System.ipynb" application.I have found that this application could not run correct.Could you help me?

**Comment by freshrich001** [comment]
I have copied all code in your article.Like this below:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split


dataset = pd.read_csv('/opt/download/books/ratings.csv')
train, test = train_test_split(dataset, test_size=0.2, random_state=42)
n_users = len(dataset.user_id.unique())
n_books = len(dataset.book_id.unique())

from keras.layers import Input, Embedding, Flatten, Dot, Dense
from keras.models import Model

book_input = Input(shape=[1], name="Book-Input")
book_embedding = Embedding(n_books, 5, name="Book-Embedding")(book_input)
book_vec = Flatten(name="Flatten-Books")(book_embedding)

user_input = Input(shape=[1], name="User-Input")
user_embedding = Embedding(n_users, 5, name="User-Embedding")(user_input)
user_vec = Flatten(name="Flatten-Users")(user_embedding)

prod = Dot(name="Dot-Product", axes=1)([book_vec, user_vec])
model = Model([user_input, book_input], prod)
model.compile('adam', 'mean_squared_error')

history = model.fit([train.user_id,train.book_id], train.rating, epochs=10, verbose=1)
model.save('regression_model.h5')

**Comment by freshrich001** [comment]
And the error is like this , "tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[15,0] = 10000 is not in [0, 10000)
         [[{{node Book-Embedding/embedding_lookup}}]]"

**Comment by freshrich001** [comment]
How to use the model?I write the code like this below:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow import keras
from keras.layers import Input, Embedding, Flatten, Dot, Dense
from keras.models import Model
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('/opt/download/books/ratings.csv')
model = keras.models.load_model('regression_model.h5')
book_data = np.array(list(set(dataset.book_id)))
user = np.array([1 for i in range(len(book_data))])
predictions = model.predict([user, book_data])
predictions = np.array([a[0] for a in predictions])
recommended_book_ids = (-predictions).argsort()[:5]
print(recommended_book_ids)
print(predictions[recommended_book_ids])
I thinks this is not right.Could you tell me how to use the model correct.
Very thanks.

**Comment by TannerGilbert** [comment]
I'm not sure what you mean. You can fin the whole code in the Recommendation System folder. 

https://github.com/TannerGilbert/Tutorials/blob/master/Recommendation%20System/Recommendation%20System.ipynb
