### ISSUE TITLE
Semantic segmentation own dataset

### ISSUE THREAD

**Issue by Olliver2020** [TannerGilbert/Tutorials#28]
Hello I am trying to do training on my own dataset. I went through tutorial with no problem but Im having problem with my own dataset. I labeled my dataset using labelme in python then generated a pascal voc dataset. Its quite different from camvid dataset. could you help?

**Comment by TannerGilbert** [comment]
I'd recommend to try [Detectron2](https://github.com/facebookresearch/detectron2) an excellent object detection and instance segmentation framework. I also have a tutorial that shows how to train on a custom dataset labeled with labelme:

- [Detectron2 Train a Instance Segmentation Model](https://gilberttanner.com/blog/detectron2-train-a-instance-segmentation-model)
