### ISSUE TITLE
python: can't open file 'generate_tfrecord.py': [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by izyanzayn** [TannerGilbert/Tutorials#29]
sir, i tried to do like this but not in the same folder as in research/object_detection instead i create new folder in desktop and save all the images, train and test images, the xml files in to that folder. i hve already done the train and test.csv with no error but when i try to run code python generate_tfrecord.py ---> python generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record --image_dir=test_labels" with "--image_dir=test_labels"
and it shows the error:
python: can't open file 'generate_tfrecord.py': [Errno 2] No such file or directory.
![Annotation 2020-05-13 0951e337](https://user-images.githubusercontent.com/64320085/81762874-5497e200-9500-11ea-8981-e917628175e5.png)

which cmd directory should i run the code ?
is it from models/research/object_detection (download from github repo) ?
![Annotation 2020-05-13 0951337](https://user-images.githubusercontent.com/64320085/81762916-6ed1c000-9500-11ea-9dea-5fe27af916f6.png)
OR
(venv) C:\Users\HP 14\Desktop\IDENTIMEtf\object_detection\data (my own folder in desktop) ?
![Annotation 2020-05-13 095137](https://user-images.githubusercontent.com/64320085/81762952-8d37bb80-9500-11ea-9c33-55cd4efd7c28.png)
2. should i move all the images (my own folder) from current dekstop folder to models/research/object_detection (from github repo) ?

**Comment by TannerGilbert** [comment]
You don't need to move the folder if you don't want to but it's certainly easier. If you don't move the folder you'll have to make sure that all the files are in the right place.

For example you are getting the error above because you don't have the generate_tfrecord.py file inside the folder you're executing the command from.
