### ISSUE TITLE
Cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by abdou31** [TannerGilbert/Tutorials#30]
Hello, When I try to run the` main_train.py`, I got this error :
>from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'

Please how can I solve it????

**Comment by TannerGilbert** [comment]
This error occurs if the protobuf libraries aren't compiled correctly. Check ou the [Protobuf Installation/Compilation section](https://gilberttanner.com/blog/installing-the-tensorflow-object-detection-api#protobuf-installation-compilation) in my [installation guide](https://gilberttanner.com/blog/installing-the-tensorflow-object-detection-api) for a step-by-step guide on how to correctly compile the protobuf libraries.

If this doesn't solve your problem take a look at the following Github issues:
- https://github.com/tensorflow/models/issues/1595
- https://github.com/tensorflow/models/issues/6148
