### ISSUE TITLE
Could not load DLL 'lib_lightgbm'

### ISSUE THREAD

**Issue by mjanot** [TannerGilbert/Tutorials#35]
Hi,
I am reading your tutorial for the first time. I loaded it into the Visual Studio project. Project compiles, but gets an error on startup:

{"Could not load DLL 'lib_lightgbm': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

in private static void Evaluate(MLContext mlContext, IDataView trainingDataView, IEstimator<ITransformer> trainingPipeline) method.

Can you help somehow?

Visual Studio 2019 Community, x64

**Comment by TannerGilbert** [comment]
I haven't experienced that error myself. Check out the following issues and let me know if they solved your problem

- https://github.com/dotnet/machinelearning/issues/1945
- https://github.com/dotnet/machinelearning/issues/2533
