### ISSUE TITLE
Error in importing the ludwig module.

### ISSUE THREAD

**Issue by Samar-080301** [TannerGilbert/Tutorials#37]
**Describe the bug**
There is a little syntax error, that's causing traceback. The bug is that `LudwigModel` not found in `ludwig`
And line no. 19 is causing `ValueError: At least one between dataset and training_set must be not None`
**To Reproduce**
1. Run `Tutorials\Uber Ludwig Introduction\python_exmple.py`
2. See error

**Expected behavior**
It should run seamlessly but there are some errors

**Desktop (please complete the following information):**
 - notebook: google colab

**Additional context**
Can I please rectify the errors?

**Comment by Samar-080301** [comment]
@TannerGilbert Please look into the issue. Thank You!

**Comment by TannerGilbert** [comment]
The code changed with the newest version of Ludwig (0.3):

Correct code:
```
from ludwig.api import LudwigModel
import pandas as pd

df = pd.read_csv('Tweets.csv')
print(df.head())

model_definition = {
    'input_features':[
        {'name':'text', 'type':'text'},
    ],
    'output_features': [
        {'name': 'airline_sentiment', 'type': 'category'}
    ]
}

print('creating model')
model = LudwigModel(model_definition)
print('training model')
train_stats, _, _ = model.train(dataset=df)
```

I'll try to update all the code the upcoming days

**Comment by TannerGilbert** [comment]
I just updated the code and article to work with the newest version of Uber Ludwig.
