### ISSUE TITLE
new user

### ISSUE THREAD

**Issue by lukaspetersson** [TannerGilbert/Tutorials#4]
I wonder how you would go about making a recommendation for a new user that is not in the database. Say the new user has read the books with number [2, 77, 2001, 5300, 5399] and given them the ratings [2, 4, 5, 3, 3].

**Comment by TannerGilbert** [comment]
Hello Lukas,

I just answered your question on Youtube and will just paste my answer here so everyone can see. Hope it answers your question. If it doesn't feel free to ask further questions.

The handling of new users was always a problem for these kind of systems. For your example I would just but the new user iniside the data-set and retrain the model for one epoch and see if this works but the problem even gets worse when you need to recommend a book to a user who never rated a book before. For this you have multiple options like recommending the most popular books or the books with the highest bias ... . For more information check out the cold start problem: https://en.wikipedia.org/wiki/Cold_start_(computing) Hope this helped.﻿

**Comment by CartierPierre** [comment]
Hi, 

> The handling of new users was always a problem for these kind of systems. For your example I would just but the new user iniside the data-set and retrain the model for one epoch and see if this works

In my case, I suppose all new user rated some books, for each one, I have to retrain the model ? The model will stay stable ?

In fact, I have a binary matrix of user/product matching with 1 (kind of sparse matrix), and filling with 0 non-matching user/product. Which system can take a new row in a trained model, without retrain ?
