### ISSUE TITLE
The link to the model zoo is dead

### ISSUE THREAD

**Issue by KommuSoft** [TannerGilbert/Tutorials#45]
**In the object detection tutorial the link to the model zoo is dead**

When clicking on the link "See the [detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) for a list of other models...", the link points to a 404 page.

**To Reproduce**
1. visit the [tutorial on object detection](https://github.com/TannerGilbert/Tutorials/blob/master/Tensorflow%20Object%20Detection/object_detection_tutorial.ipynb)
2. click on the link with the model zoo;
3. see that it raises a 404.

**Expected behavior**
It should point to the detection model zoo, likely [this link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)

**Desktop:**
 - OS: Ubuntu
 - Browser Firefox
 - Version n/a

**Comment by TannerGilbert** [comment]
I updated the links. Still I'd recommend to use my updated Tensorflow 2 scripts instead:
* [Tensorflow-Object-Detection-with-Tensorflow-2.0](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0)
* [Tensorflow-Object-Detection-API-Train-Model](https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-Train-Model)
