### ISSUE TITLE
Scraping comments for each post together

### ISSUE THREAD

**Issue by Vibhuarvind** [TannerGilbert/Tutorials#54]
what if I want to scrape posts along with the comment on each post into csv? How do i do it?

**Comment by TannerGilbert** [comment]
This depends on if the website is static or dynamic. If it's static, you can scrape it with BeautifulSoup and save the results into a CSV. If the website is dynamic, you'll need a tool that allows you to render the browser like Selenium. For more information, check out ['Python Web Scraping - Dynamic Websites'](https://www.tutorialspoint.com/python_web_scraping/python_web_scraping_dynamic_websites.htm).
