### ISSUE TITLE
Convert model into TensorRT model

### ISSUE THREAD

**Issue by JCP13** [TannerGilbert/Tutorials#7]
Hi Gilbert,

Thank you so much for the great tutorials "Tensorflow Object Detection". Can you please provide a tutorial on how to convert a model (like the one you used on "Tensorflow Object Detection") to TensorRT?

Thank you in advance.

**Comment by TannerGilbert** [comment]
I found [this utility](https://github.com/tensorflow/models/tree/master/research/tensorrt) provided by Tensorflow to convert SavedModels or FrozenGraphs to TensorRT. 

Hopefully this answers your question. I will try it out myself in the upcoming days and I will let you know if I face any issues and how I resolved them. If this didn't help feel free to reopen the issue

**Comment by JCP13** [comment]
I will give it a try this weekend, thank you for the prompt reply.

**Comment by JCP13** [comment]
Hi Gilbert,

fantastic! looking forward to your results.

**Comment by JCP13** [comment]
@TannerGilbert, hi, did you have a chance to try out the utility?

**Comment by TannerGilbert** [comment]
They changed the location of the utility to: https://github.com/tensorflow/tensorrt

Just tried it out with Tensorflow 1.8 and Tensorflow 2 and it seems to work fine.
