### ISSUE TITLE
Using model_ssd_mobilenet_v1_coco_2018_01_28

### ISSUE THREAD

**Issue by JCP13** [TannerGilbert/Tutorials#8]
Is it possible to use model_ssd_mobilenet_v1_coco_2018_01_28? If so, what changes do I have to make?

Thank you in advance.

**Comment by TannerGilbert** [comment]
To use another model architecture you only need to replace the faster_rcnn_inception_v2_pets.config file with a file for this architecture. But don't forget to make the changes regarding the input_path and label map. You can find all available configs under the [samples/configs folder](https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs).

**Comment by JCP13** [comment]
Thank you, I will give it a try this weekend.
