### ISSUE TITLE
Running The training but it could not be utilizing GPU

### ISSUE THREAD

**Issue by angyee** [TannerGilbert/Tutorials#9]
Hi

I am working same as your video tutorial, now running the training process, 

but after running $ nvidia-smi 
not showing any running process, I have GTX 2080 GPU

@TannerGilbert

**Comment by TannerGilbert** [comment]
Hello angyee. This repository includes code for many of my articles/video. Can you tell me what video you are referring to?

**Comment by angyee** [comment]
https://www.youtube.com/watch?v=HjiBbChYRDw

**Comment by TannerGilbert** [comment]
Check out how to install cuda correctly:

- https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
- https://www.youtube.com/watch?v=TgGm27_kroI
